### ISSUE TITLE
all entitys enter tardis

### ISSUE THREAD

**Issue by foxy-commentating-bread** [M-D-Team/ait#229]
this one is pretty self explanatory, allow things like horses, camels, wardens, and iron golems to walk into the tardis

**Comment by Duzos** [comment]
they should be able to

**Comment by foxy-commentating-bread** [comment]
> they should be able to

they cant however i tried with the 3.1 beta and immersive

**Comment by Loqor** [comment]
Most entities can, but immersive portals prevents their entrance.
